---

- name: sysctl tweaking
  ansible.builtin.template:
    src: "sysctl/{{ item }}"
    dest: "/etc/sysctl.d/{{ item }}"
    mode: 0644
    owner: root
    group: root
  loop:
    - 95-tweaks.conf
    - 99-ipv6.conf

- name: apply hardened/hardened sysctl
  ansible.builtin.systemd:
    name: systemd-sysctl.service
    state: restarted
    daemon_reload: true
  changed_when: false
